version: '3.8'

services:
  db:
    image: postgres:14-alpine
    container_name: neverpay_db_prod
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: neverpay
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d neverpay"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: neverpay_app_prod
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: production
      DATABASE_URL: "postgresql://user:password@db:5432/neverpay?schema=public"
      API_KEY: ${API_KEY} # Make sure to set this in your environment
      PORT: 3000
    command: sh -c "npx prisma migrate deploy && npm start"

volumes:
  postgres_data: